name: Tagged Release Asset Download
description: Downloads an asset from a Github Release with support for tag prefixes

branding:
  icon: download-cloud
  color: purple

runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  repo:
    description: the 'owner/repo' of the repository to download from
    required: false
    default: ""
  version:
    description: the version of the release to download from (defaults to latest)
    required: false
    default: latest
  prefix:
    description: the tag prefix to use, useful in monorepos with path prefix for tags (defaults to v)
    required: false
    default: v
  file:
    description: the name of the file in the release to download
    required: true
  out:
    description: the directory where the file will be stored on local disk
    required: false
    default: ""
  mode:
    description: the mode of the file after downloading it from the release
    required: false
    default: "644"
  token:
    description: an optional Access Token to access repository
    required: false
    default: ""
  unpack:
    description: unpack the asset if it's of type .tar.gz, .tgz or .zip
    required: false
    default: "false"

outputs:
  out:
    description: The location on local disk where the file was stored
  version:
    description: The version of the release or tag
  asset:
    description: JSON with details about found asset
